version: '3.3'
services:
    # Web service
    web:
        # Get DockerFile for build
        build: ./app
        # Ports expose
        ports:
            - "5000:5000"
        # Create volume
        volumes:
            - ./app:/app
        # Link with redis
        depends_on:
            - redis-container
        # Create networks for communication
        networks:
            - front
            - db
        # Restart on changes
        restart: unless-stopped
      
    # db service
    db:
        # Get DockerFile for build
        build: ./db
        # Ports expose
        ports:
            - "3307:3307"

        environment:
          MYSQL_DATABASE: games
          MYSQL_USER: ${SQL_USER}
          MYSQL_PASSWORD: ${SQL_PASSWORD}
          MYSQL_ROOT_PASSWORD: root 
        # Create volume
        volumes:
            - ./db:/db
        # Link with redis
        depends_on:
            - redis-container
        # Create networks for communication
        networks:
            - front
            - db
        # Restart on changes
        restart: unless-stopped

    redis-container:
        image: redis
        networks: 
            - db

networks: 
    front:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
    db: